### ISSUE TITLE
Segfault with MKL BLAS level 2 update matrices

### ISSUE THREAD

**Issue by imciner2** [osqp/osqp#459]
When using the MKL backend with the CG solver, the update matrix test suite segfaults when doing a matrix-vector multiplication in the solver.

Backtrace (from branch modernizing the testsuite in https://github.com/osqp/osqp/pull/460):
```
Thread 1 "osqp_tester" received signal SIGSEGV, Segmentation fault.
0x0000000000514772 in OSQPMatrix_Atxpy (A=0x0, x=0x5d1160, y=0x5bc370, alpha=1, beta=1) at /home/imcinerney/dev/osqp/code/master/algebra/mkl/matrix.c:194
194	  if(A->symmetry == NONE){
(gdb) bt
#0  0x0000000000514772 in OSQPMatrix_Atxpy (A=0x0, x=0x5d1160, y=0x5bc370, alpha=1, beta=1) at /home/imcinerney/dev/osqp/code/master/algebra/mkl/matrix.c:194
#1  0x000000000051637a in solve_linsys_mklcg (s=0x648fe0, b=0x64a230, admm_iter=1)
    at /home/imcinerney/dev/osqp/code/master/algebra/mkl/lin_sys/indirect/mkl-cg_interface.c:145
#2  0x000000000050a49c in update_xz_tilde (solver=0x5c7450, admm_iter=1) at /home/imcinerney/dev/osqp/code/master/src/auxil.c:174
#3  0x000000000050836d in osqp_solve (solver=0x5c7450) at /home/imcinerney/dev/osqp/code/master/src/osqp_api.c:435
#4  0x0000000000466594 in test_update () at /home/imcinerney/dev/osqp/code/master/tests/update_matrices/test_update_matrices.h:167
#5  0x000000000046cfe0 in ____C_A_T_C_H____T_E_S_T____238 () at /home/imcinerney/dev/osqp/code/master/tests/osqp_tester.cpp:151
#6  0x00000000004210a8 in Catch::TestInvokerAsFunction::invoke (this=0x5ba3d0)
    at /home/imcinerney/dev/osqp/code/master/build-mkl/_deps/catch2-src/single_include/catch2/catch.hpp:14317
#7  0x00000000004203ef in Catch::TestCase::invoke (this=0x5c1678)
    at /home/imcinerney/dev/osqp/code/master/build-mkl/_deps/catch2-src/single_include/catch2/catch.hpp:14156
#8  0x000000000041b037 in Catch::RunContext::invokeActiveTestCase (this=0x7fffffffcfb0)
    at /home/imcinerney/dev/osqp/code/master/build-mkl/_deps/catch2-src/single_include/catch2/catch.hpp:13016
#9  0x000000000041adbb in Catch::RunContext::runCurrentTest (this=0x7fffffffcfb0, redirectedCout="", redirectedCerr="")
    at /home/imcinerney/dev/osqp/code/master/build-mkl/_deps/catch2-src/single_include/catch2/catch.hpp:12989
#10 0x0000000000419a49 in Catch::RunContext::runTest (this=0x7fffffffcfb0, testCase=...)
    at /home/imcinerney/dev/osqp/code/master/build-mkl/_deps/catch2-src/single_include/catch2/catch.hpp:12750
#11 0x000000000041c75f in Catch::(anonymous namespace)::TestGroup::execute (this=0x7fffffffcfa0)
    at /home/imcinerney/dev/osqp/code/master/build-mkl/_deps/catch2-src/single_include/catch2/catch.hpp:13343
#12 0x000000000041da3b in Catch::Session::runInternal (this=0x7fffffffd2b0)
    at /home/imcinerney/dev/osqp/code/master/build-mkl/_deps/catch2-src/single_include/catch2/catch.hpp:13549
#13 0x000000000041d780 in Catch::Session::run (this=0x7fffffffd2b0)
    at /home/imcinerney/dev/osqp/code/master/build-mkl/_deps/catch2-src/single_include/catch2/catch.hpp:13505
#14 0x00000000004948e3 in Catch::Session::run<char> (this=0x7fffffffd2b0, argc=1, argv=0x7fffffffd568)
    at /home/imcinerney/dev/osqp/code/master/build-mkl/_deps/catch2-src/single_include/catch2/catch.hpp:13227
#15 0x0000000000432a95 in main (argc=1, argv=0x7fffffffd568)
    at /home/imcinerney/dev/osqp/code/master/build-mkl/_deps/catch2-src/single_include/catch2/catch.hpp:17504
```

**Comment by imciner2** [comment]
Its possible this might be fixed by the memory management changes in https://github.com/osqp/osqp/pull/457, but the backtrace seems to suggest a matrix is not getting updated properly rather than an issue with the user-provided arrays.
