### ISSUE TITLE
Null pointer in CUDA backend when using polish with no active set

### ISSUE THREAD

**Issue by imciner2** [osqp/osqp#463]
When there is no active set present in a problem and the CUDA backend tries to perform the polishing step, there is a NULL pointer error thrown by CUDA:
```
Filters: test_no_active_set
-----------------------------------------------------------------
           OSQP v0.0.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2021
-----------------------------------------------------------------
problem:  variables n = 2, constraints m = 3
          nnz(P) + nnz(A) = 6
settings: algebra = CUDA,
          linear system solver = CUDA Preconditioned Conjugate Gradient,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 4000
          check_termination: on (interval 5),
          time_limit: 1.00e+10 sec,
          scaling: on, scaled_termination: off
          warm starting: on, polishing: off, 
iter   objective    prim res   dual res   rho        time
   1   0.0000e+00   0.00e+00   0.00e+00   1.00e-01   8.10e-01s
   5   0.0000e+00   0.00e+00   0.00e+00   1.00e-01   8.11e-01s

status:               solved
number of iterations: 5
optimal objective:    0.0000
run time:             8.11e-01s
optimal rho estimate: 1.00e-06

-----------------------------------------------------------------
           OSQP v0.0.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2021
-----------------------------------------------------------------
problem:  variables n = 2, constraints m = 3
          nnz(P) + nnz(A) = 6
settings: algebra = CUDA,
          linear system solver = CUDA Preconditioned Conjugate Gradient,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 4000
          check_termination: on (interval 5),
          time_limit: 1.00e+10 sec,
          scaling: on, scaled_termination: off
          warm starting: on, polishing: on, 
iter   objective    prim res   dual res   rho        time
   1   0.0000e+00   0.00e+00   0.00e+00   1.00e-01   5.73e-02s
   5   0.0000e+00   0.00e+00   0.00e+00   1.00e-01   5.80e-02s
 ** On entry to cusparseSpMV() parameter number 7 (vecY) had an illegal value: NULL pointer

CUDA error at /home/b63738im/dev/optimization/osqp/c_code/algebra/cuda/src/cuda_lin_alg.cu:946 code=3(CUSPARSE_STATUS_INVALID_VALUE) "cusparseSpMV( CUDA_handle->cusparseHandle, CUSPARSE_OPERATION_NON_TRANSPOSE, &alpha, A->SpMatDescr, vecx, &beta, vecy, CUDA_FLOAT, CUSPARSE_SPMV_ALG_DEFAULT, A->SpMatBuffer)" 
```

**Comment by imciner2** [comment]
The relevant backtrace for this error is
```
#6  0x0000000000522ee9 in check<cusparseStatus_t> (result=CUSPARSE_STATUS_INVALID_VALUE, 
    func=0x5bfe08 "cusparseSpMV( CUDA_handle->cusparseHandle, CUSPARSE_OPERATION_NON_TRANSPOSE, &alpha, A->SpMatDescr, vecx, &beta, vecy, CUDA_FLOAT, CUSPARSE_SPMV_ALG_DEFAULT, A->SpMatBuffer)", 
    file=0x5bf710 "/home/b63738im/dev/optimization/osqp/c_code/algebra/cuda/src/cuda_lin_alg.cu", line=946)
    at /home/b63738im/dev/optimization/osqp/c_code/algebra/cuda/include/helper_cuda.h:589
#7  0x000000000052f380 in cuda_mat_Axpy (A=0x1a846f50, vecx=0x19e73160, vecy=0x0, alpha=1, beta=-1)
    at /home/b63738im/dev/optimization/osqp/c_code/algebra/cuda/src/cuda_lin_alg.cu:946
#8  0x000000000051cb2c in solve_linsys_cudapcg (s=0x19e73a70, b=0x1a846fa0, admm_iter=1)
    at /home/b63738im/dev/optimization/osqp/c_code/algebra/cuda/lin_sys/indirect/cuda_pcg_interface.cu:245
#9  0x000000000051b912 in polish (solver=0x1a5fc3e0) at /home/b63738im/dev/optimization/osqp/c_code/src/polish.c:353
#10 0x0000000000515347 in osqp_solve (solver=0x1a5fc3e0)
    at /home/b63738im/dev/optimization/osqp/c_code/src/osqp_api.c:681
#11 0x0000000000465ea5 in test_unconstrained_solve ()
    at /home/b63738im/dev/optimization/osqp/c_code/tests/unconstrained/test_unconstrained.h:48
```
Which says that the vector `S->vecz` n the PCG solver is NULL. This makes sense since that vector is only allocated when there actually are constraints being solved for, and is not allocated otherwise.
