### ISSUE TITLE
NULL pointer in CUDA backend when using polish on an unconstrained problem

### ISSUE THREAD

**Issue by imciner2** [osqp/osqp#464]
When solving an unconstrained problem with the CUDA backend with polishing enabled, there is a NULL pointer error when doing a matrix-vector multiplication:
```
Filters: test_unconstrained
-----------------------------------------------------------------
           OSQP v0.0.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2021
-----------------------------------------------------------------
problem:  variables n = 5, constraints m = 0
          nnz(P) + nnz(A) = 5
settings: algebra = CUDA,
          linear system solver = CUDA Preconditioned Conjugate Gradient,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 4000
          check_termination: on (interval 5),
          time_limit: 1.00e+10 sec,
          scaling: on, scaled_termination: off
          warm starting: on, polishing: off, 
iter   objective    prim res   dual res   rho        time
   1  -1.2294e+01   0.00e+00   1.42e+00   1.00e-01   8.20e-01s
  25  -1.9210e+01   0.00e+00   6.61e-06   1.00e-06   8.24e-01s

status:               solved
number of iterations: 25
optimal objective:    -19.2098
run time:             8.25e-01s
optimal rho estimate: 1.00e-06

-----------------------------------------------------------------
           OSQP v0.0.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2021
-----------------------------------------------------------------
problem:  variables n = 5, constraints m = 0
          nnz(P) + nnz(A) = 5
settings: algebra = CUDA,
          linear system solver = CUDA Preconditioned Conjugate Gradient,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 4000
          check_termination: on (interval 5),
          time_limit: 1.00e+10 sec,
          scaling: on, scaled_termination: off
          warm starting: on, polishing: on, 
iter   objective    prim res   dual res   rho        time
   1  -1.2294e+01   0.00e+00   1.42e+00   1.00e-01   3.34e-02s
  25  -1.9210e+01   0.00e+00   6.61e-06   1.00e-06   3.76e-02s
 ** On entry to cusparseSpMV() parameter number 4 (matA) had an illegal value: NULL pointer

CUDA error at /home/b63738im/dev/optimization/osqp/c_code/algebra/cuda/src/cuda_lin_alg.cu:946 code=3(CUSPARSE_STATUS_INVALID_VALUE) "cusparseSpMV( CUDA_handle->cusparseHandle, CUSPARSE_OPERATION_NON_TRANSPOSE, &alpha, A->SpMatDescr, vecx, &beta, vecy, CUDA_FLOAT, CUSPARSE_SPMV_ALG_DEFAULT, A->SpMatBuffer)" 
```

**Comment by imciner2** [comment]
Relevant backtrace:
```
#6  0x0000000000522ee9 in check<cusparseStatus_t> (result=CUSPARSE_STATUS_INVALID_VALUE, 
    func=0x5bfe08 "cusparseSpMV( CUDA_handle->cusparseHandle, CUSPARSE_OPERATION_NON_TRANSPOSE, &alpha, A->SpMatDescr, vecx, &beta, vecy, CUDA_FLOAT, CUSPARSE_SPMV_ALG_DEFAULT, A->SpMatBuffer)", 
    file=0x5bf710 "/home/b63738im/dev/optimization/osqp/c_code/algebra/cuda/src/cuda_lin_alg.cu", line=946) at /home/b63738im/dev/optimization/osqp/c_code/algebra/cuda/include/helper_cuda.h:589
#7  0x000000000052f380 in cuda_mat_Axpy (A=0x1a846f50, vecx=0x19e73160, vecy=0x0, alpha=1, beta=-1) at /home/b63738im/dev/optimization/osqp/c_code/algebra/cuda/src/cuda_lin_alg.cu:946
#8  0x000000000051cb2c in solve_linsys_cudapcg (s=0x19e73a70, b=0x1a846fa0, admm_iter=1) at /home/b63738im/dev/optimization/osqp/c_code/algebra/cuda/lin_sys/indirect/cuda_pcg_interface.cu:245
#9  0x000000000051b912 in polish (solver=0x1a5fc3e0) at /home/b63738im/dev/optimization/osqp/c_code/src/polish.c:353
#10 0x0000000000515347 in osqp_solve (solver=0x1a5fc3e0) at /home/b63738im/dev/optimization/osqp/c_code/src/osqp_api.c:681
#11 0x0000000000465ea5 in test_unconstrained_solve () at /home/b63738im/dev/optimization/osqp/c_code/tests/unconstrained/test_unconstrained.h:48
```
The matrix A here is `S->A` which is the matrix of the active constraints, so this is a similar problem to https://github.com/osqp/osqp/issues/463, where when there is no active set the vectors/matrices aren't actually created and so using them is not going to work.
