### ISSUE TITLE
OSQP Python Interface is incompatible with Numpy 1.24

### ISSUE THREAD

**Issue by boschmic** [osqp/osqp#498]
The OSQP interface is incompatible with numpy 1.24 because OSQP is using a deprecated field `np.int` that has been removed in the latest numpy release (https://numpy.org/devdocs/release/1.20.0-notes.html#using-the-aliases-of-builtin-types-like-np-int-is-deprecated)

# How to reproduce

Install numpy 1.24, i.e here is my PDM config:

```
[project]
dependencies = [
    "numpy>=1.24",
    "osqp>=0.6.2.post8",
    "scipy>=1.9.3",
]
requires-python = ">=3.9"
```

Run following code:

```
import numpy as np
import osqp
inf = np.inf
A = np.array([[ 1.,  0.],
        [ 0.,  1.],
        [-3.,  1.],
        [ 1.,  2.]])
l = np.array([-inf,  -3., -inf, -inf])
u = np.array([inf, inf,  6.,  4.])
solver = osqp.OSQP()
solver.setup(A=A, l=l, u=u)
solver.solve()
```

Error:

```
Traceback (most recent call last):
  main.py", line 17, in <module>
    solver.setup(A=A, l=l, u=u)
  File /.venv/lib/python3.9/site-packages/osqp/interface.py", line 36, in setup
    unpacked_data, settings = utils.prepare_data(P, q, A, l, u, **settings)
  File "/.venv/lib/python3.9/site-packages/osqp/utils.py", line 74, in prepare_data
    np.zeros((0,), dtype=np.int),
  File "/.venv/lib/python3.9/site-packages/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'int'
```

**Comment by boschmic** [comment]
Oops, wrong repo.
And there is already an issue: https://github.com/osqp/osqp-python/issues/104
