### ISSUE TITLE
Install with Python 3.12.1 fails due to QDLDL

### ISSUE THREAD

**Issue by maximiliandegner** [osqp/osqp#599]
Installing OSQP for Python using `python -m pip install osqp` fails when using python 3.12.1 (and having pip version 23.3.2). The exact error can be found below but the problem stems from QDLDL which apparently does not work with Python 3.12.1. I tried installing OSQP for Python 3.11.7 and this worked like a charm (without installing cmake as suggested in the traceback message). Find the results below.
I am running a fairly fresh Windows 11 installation on my machine and using new venvs for the installation.

**For Python 3.12.1:**
```
(venv) PS C:\Users\maxim\Documents\Masterthesis\Code> pip3 install osqp
Collecting osqp
  Using cached osqp-0.6.3.tar.gz (228 kB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [122 lines of output]
      Collecting oldest-supported-numpy
        Using cached oldest_supported_numpy-2023.12.12-py3-none-any.whl.metadata (9.8 kB)
      Collecting setuptools>=40.8.0
        Using cached setuptools-69.0.2-py3-none-any.whl.metadata (6.3 kB)
      Collecting wheel
        Using cached wheel-0.42.0-py3-none-any.whl.metadata (2.2 kB)
      Collecting setuptools_scm>=6.2
        Using cached setuptools_scm-8.0.4-py3-none-any.whl.metadata (6.4 kB)
      Collecting qdldl
        Using cached qdldl-0.1.7.post0.tar.gz (70 kB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Installing backend dependencies: started
        Installing backend dependencies: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'done'
      Collecting numpy==1.26.2 (from oldest-supported-numpy)
        Using cached numpy-1.26.2-cp312-cp312-win_amd64.whl.metadata (61 kB)
      Collecting packaging>=20 (from setuptools_scm>=6.2)
        Using cached packaging-23.2-py3-none-any.whl.metadata (3.2 kB)
      Collecting typing-extensions (from setuptools_scm>=6.2)
        Using cached typing_extensions-4.9.0-py3-none-any.whl.metadata (3.0 kB)
      Collecting scipy>=0.13.2 (from qdldl)
        Using cached scipy-1.11.4-cp312-cp312-win_amd64.whl.metadata (60 kB)
      Using cached oldest_supported_numpy-2023.12.12-py3-none-any.whl (4.9 kB)
      Using cached numpy-1.26.2-cp312-cp312-win_amd64.whl (15.5 MB)
      Using cached setuptools-69.0.2-py3-none-any.whl (819 kB)
      Using cached wheel-0.42.0-py3-none-any.whl (65 kB)
      Using cached setuptools_scm-8.0.4-py3-none-any.whl (42 kB)
      Using cached packaging-23.2-py3-none-any.whl (53 kB)
      Using cached scipy-1.11.4-cp312-cp312-win_amd64.whl (43.7 MB)
      Using cached typing_extensions-4.9.0-py3-none-any.whl (32 kB)
      Building wheels for collected packages: qdldl
        Building wheel for qdldl (pyproject.toml): started
        Building wheel for qdldl (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error

        Building wheel for qdldl (pyproject.toml) did not run successfully.
        exit code: 1

        [73 lines of output]
        running bdist_wheel
        running build
        running build_ext
        Traceback (most recent call last):
          File "<string>", line 81, in build_extensions
          File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.496.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 466, in check_output     
            return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.496.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 548, in run
            with Popen(*popenargs, **kwargs) as process:
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.496.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 1026, in __init__        
            self._execute_child(args, executable, preexec_fn, close_fds,
          File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.496.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 1538, in _execute_child  
            hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden

        During handling of the above exception, another exception occurred:

        Traceback (most recent call last):
          File "C:\Users\maxim\Documents\Masterthesis\Code\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>  
            main()
          File "C:\Users\maxim\Documents\Masterthesis\Code\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main      
            json_out['return_val'] = hook(**hook_input['kwargs'])
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "C:\Users\maxim\Documents\Masterthesis\Code\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 251, in build_wheel
            return _build_backend().build_wheel(wheel_directory, config_settings,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "C:\Users\maxim\AppData\Local\Temp\pip-build-env-b16yzye8\overlay\Lib\site-packages\setuptools\build_meta.py", line 404, in build_wheel
            return self._build_with_temp_dir(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "C:\Users\maxim\AppData\Local\Temp\pip-build-env-b16yzye8\overlay\Lib\site-packages\setuptools\build_meta.py", line 389, in _build_with_temp_dir   
            self.run_setup()
          File "C:\Users\maxim\AppData\Local\Temp\pip-build-env-b16yzye8\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
            exec(code, locals())
          File "<string>", line 113, in <module>
          File "C:\Users\maxim\AppData\Local\Temp\pip-build-env-b16yzye8\overlay\Lib\site-packages\setuptools\__init__.py", line 103, in setup
            return distutils.core.setup(**attrs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "C:\Users\maxim\AppData\Local\Temp\pip-build-env-b16yzye8\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
            return run_commands(dist)
                   ^^^^^^^^^^^^^^^^^^
          File "C:\Users\maxim\AppData\Local\Temp\pip-build-env-b16yzye8\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands      
            dist.run_commands()
          File "C:\Users\maxim\AppData\Local\Temp\pip-build-env-b16yzye8\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands      
            self.run_command(cmd)
          File "C:\Users\maxim\AppData\Local\Temp\pip-build-env-b16yzye8\overlay\Lib\site-packages\setuptools\dist.py", line 963, in run_command
            super().run_command(command)
          File "C:\Users\maxim\AppData\Local\Temp\pip-build-env-b16yzye8\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command       
            cmd_obj.run()
          File "C:\Users\maxim\AppData\Local\Temp\pip-build-env-b16yzye8\normal\Lib\site-packages\wheel\bdist_wheel.py", line 368, in run
            self.run_command("build")
          File "C:\Users\maxim\AppData\Local\Temp\pip-build-env-b16yzye8\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command        
            self.distribution.run_command(command)
          File "C:\Users\maxim\AppData\Local\Temp\pip-build-env-b16yzye8\overlay\Lib\site-packages\setuptools\dist.py", line 963, in run_command
            super().run_command(command)
          File "C:\Users\maxim\AppData\Local\Temp\pip-build-env-b16yzye8\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command       
            cmd_obj.run()
          File "C:\Users\maxim\AppData\Local\Temp\pip-build-env-b16yzye8\overlay\Lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run      
            self.run_command(cmd_name)
          File "C:\Users\maxim\AppData\Local\Temp\pip-build-env-b16yzye8\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command        
            self.distribution.run_command(command)
          File "C:\Users\maxim\AppData\Local\Temp\pip-build-env-b16yzye8\overlay\Lib\site-packages\setuptools\dist.py", line 963, in run_command
            super().run_command(command)
          File "C:\Users\maxim\AppData\Local\Temp\pip-build-env-b16yzye8\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command       
            cmd_obj.run()
          File "C:\Users\maxim\AppData\Local\Temp\pip-build-env-b16yzye8\overlay\Lib\site-packages\setuptools\command\build_ext.py", line 88, in run
            _build_ext.run(self)
          File "C:\Users\maxim\AppData\Local\Temp\pip-build-env-b16yzye8\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 345, in run  
            self.build_extensions()
          File "<string>", line 83, in build_extensions
        RuntimeError: CMake must be installed to build qdldl
        [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for qdldl
      Failed to build qdldl
      ERROR: Could not build wheels for qdldl, which is required to install pyproject.toml-based projects
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.``` 

**With Python 3.11.7:**
```
(venv_311) PS C:\Users\maxim\Documents\Masterthesis\Code> pip install osqp
Collecting osqp
  Obtaining dependency information for osqp from https://files.pythonhosted.org/packages/23/46/232041be3d85624ec4c20b3bdb8bd4bfb6640851901db155917e0c412aef/osqp-0.6.3-cp311-cp311-win_amd64.whl.metadata
  Downloading osqp-0.6.3-cp311-cp311-win_amd64.whl.metadata (1.8 kB)
Collecting numpy>=1.7 (from osqp)
  Obtaining dependency information for numpy>=1.7 from https://files.pythonhosted.org/packages/da/3c/3ff05c2855eee52588f489a4e607e4a61699a0742aa03ccf641c77f9eb0a/numpy-1.26.2-cp311-cp311-win_amd64.whl.metadata
  Downloading numpy-1.26.2-cp311-cp311-win_amd64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.2/61.2 kB 548.1 kB/s eta 0:00:00
Collecting scipy>=0.13.2 (from osqp)
  Obtaining dependency information for scipy>=0.13.2 from https://files.pythonhosted.org/packages/43/d0/f3cd75b62e1b90f48dbf091261b2fc7ceec14a700e308c50f6a69c83d337/scipy-1.11.4-cp311-cp311-win_amd64.whl.metadata
  Downloading scipy-1.11.4-cp311-cp311-win_amd64.whl.metadata (60 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.4/60.4 kB 1.6 MB/s eta 0:00:00
Collecting qdldl (from osqp)
  Obtaining dependency information for qdldl from https://files.pythonhosted.org/packages/f3/0c/972bd00b80aefc57c9a25ca47f802e315ce054fe72cd74d95af6c0f5b3f0/qdldl-0.1.7.post0-cp311-cp311-win_amd64.whl.metadata
  Downloading qdldl-0.1.7.post0-cp311-cp311-win_amd64.whl.metadata (1.8 kB)
Downloading osqp-0.6.3-cp311-cp311-win_amd64.whl (292 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 293.0/293.0 kB 6.0 MB/s eta 0:00:00
Downloading numpy-1.26.2-cp311-cp311-win_amd64.whl (15.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.8/15.8 MB 12.8 MB/s eta 0:00:00
Downloading scipy-1.11.4-cp311-cp311-win_amd64.whl (44.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.1/44.1 MB 12.8 MB/s eta 0:00:00
Downloading qdldl-0.1.7.post0-cp311-cp311-win_amd64.whl (85 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.1/85.1 kB 4.7 MB/s eta 0:00:00
Installing collected packages: numpy, scipy, qdldl, osqp
Successfully installed numpy-1.26.2 osqp-0.6.3 qdldl-0.1.7.post0 scipy-1.11.4```

**Comment by stonebig** [comment]
we can't get cvxpy either currently on Python-3.12 for Windows, due to osqp and qdldl  wheels not existing for Python-3.12

**Comment by imciner2** [comment]
We've recently updated and rebuilt both qdldl and osqp wheels, so I think this should be fixed.

Do you still see any issues?

**Comment by stonebig** [comment]
qdldl wheel don't exist for python-3.13. it would be nice to have them, if possible

**Comment by imciner2** [comment]
> qdldl wheel don't exist for python-3.13. it would be nice to have them, if possible

Wheels for QDLDL and Python 3.13 have now been uploaded with version v0.1.7.post5.

**Comment by imciner2** [comment]
Has this been resolved?
